import Foundation
import AnkiKit

/// Bridges the native SwiftUI UI to Anki's shared translation catalog.
///
/// `tr("some-fluent-key")` maps the Fluent key to its `(module, message)` index
/// (from the bundled `ftl_index.json`, generated by `tools/gen_ftl_index.py`)
/// and asks the engine to translate it in the collection's configured language —
/// the same catalog and mechanism Anki Desktop and AnkiDroid use. The engine
/// falls back to English when a language lacks a string; if the engine isn't
/// ready or the key is unknown, `tr` returns the key so a mistake is visible
/// rather than crashing.
///
/// The language itself is chosen when the collection is opened (see
/// `AnkiStore.boot()` / the `appLanguageOverride` setting); changing it re-opens
/// the collection so every `tr` result updates.
@MainActor
enum Loc {
    /// Fluent key -> [moduleIndex, messageIndex], loaded once from the bundle.
    private static let index: [String: [UInt32]] = {
        guard let url = Bundle.main.url(forResource: "ftl_index", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let map = try? JSONDecoder().decode([String: [UInt32]].self, from: data)
        else {
            assertionFailure("ftl_index.json missing/unreadable from the app bundle")
            return [:]
        }
        return map
    }()

    /// The engine used for translation, set when the collection opens. Weak so it
    /// follows the store's backend (a language change swaps in a new one).
    private(set) static weak var backend: Backend?

    static func configure(backend: Backend) { self.backend = backend }

    /// Translates a Fluent key in the collection's language. `args` fills string
    /// `{$var}` placeholders; `numericArgs` fills numeric ones (some plurals).
    static func tr(
        _ key: String,
        args: [String: String] = [:],
        numericArgs: [String: Double] = [:]
    ) -> String {
        guard let idx = index[key], idx.count == 2, let backend else { return key }
        return (try? backend.translateString(
            module: idx[0], message: idx[1], args: args, numericArgs: numericArgs
        )) ?? key
    }
}
